title: "DanicaStar's GitPages Blog"
description: "Good!"
url: 
baseurl: ""
author: "Danicastar"
paginate: 5
paginate_path: "/blog/page:num/"
future: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
